version: "3"
services:
  api:
    container_name: api-reallifeperktree
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      # app port : publicly exposed port
      - "8080:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    volumes:
      - "./server:/app"
  # website:
  #    container_name: web-reallifeperktree
  #   build:
  # context: .
  #      dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  # depends_on:
  #   # Depends on api container
  #   - api
# TO RUN -> docker-compose up
# starts all containers
